#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 17 02:20:29 2020

@author: SpencerAndTheMatt

Pow function
"""

class Solution:
    def myPow1(x, n):
        if n == 0:
            return 1
        if n < 0:
            x = 1/x
            n = n*(-1)
            
        while n > 0:
            return x * Solution.myPow(x, n-1)
